# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsTest
  - name: llm_gender_prediction
    model_type: llm_model
    model_spec:
      prompt: "The input field is a name entered by a person. Map it to a single value from the following list of standardised gender titles: [Male,Female,Other]. Return only standardised title, nothing else. {input[0]}"
      entity_key: user
      prompt_inputs:
        - user.Var('name')
      llm_model_name: "mistral-7b"
  - name: llm_profession_prediction
    model_type: llm_model
    model_spec:
      prompt: "The input field is a job title entered by a person. Map it to a single value from the following list of standardised job titles: [Software Engineer, Data Analyst, ML Engineer, Solutions Architect, Others]. Return only standardised title, nothing else. {input[0]}. Do it only if {input[1]} is 'US'"
      entity_key: user
      prompt_inputs:
        - user.Var('profession')
        - user.Var('country')
      llm_model_name: "mistral-7b"

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: name
          select: max(first_name)
          from: inputs/rsTest
      - entity_var:
          name: profession
          select: max(profession)
          from: inputs/rsTest
      - entity_var:
          name: country
          select: max(country)
          from: inputs/rsTest
