# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
  - name: llm_gender_prediction
    model_type: llm_model
    model_spec:
      prompt: "What is generally the most common gender of the name {input[0]}? Male, Female, or Unknown? Return only a single word, nothing else."
      entity_key: user
      prompt_inputs:
        - user.Var('name')
      llm_model_name: "mistral-7b"
      features:
        - name: llm_gender_prediction
      ids:
        - select: "user_main_id"
          type: user_id
          entity: user
  - name: llm_profession_prediction
    model_type: llm_model
    model_spec:
      prompt: "The input field is a job title entered by a person. Map it to a single value from the following list of standardised job titles: [Software Engineer, Data Analyst, ML Engineer, Solutions Architect, Others]. Return only standardised title, nothing else. {input[0]}"
      entity_key: user
      prompt_inputs:
        - user.Var('profession')
      llm_model_name: "mistral-7b"


var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: profession
          select: any_value(case when random() <0.25 then 'data analyst' when random() < 0.5 then 'sde' when random() < 0.75 then 'sde2' else 'market analyst' end )
          from: inputs/rsIdentifies
      - entity_var:
          name: name
          select: any_value(first_name)
          from: inputs/rsIdentifies
