models:
  - name: rudder_user_base_features_1
    model_type: feature_table_model
    model_spec:
      validity_time: 0s # 1 day
      entity_key: user
      vars:
          - entity_var:
              name: max_timestamp_bw_tracks_pages_1
              select: max(timestamp)
              from: inputs/rsTracks
          #days since last seen
          - entity_var:
              name: days_since_last_seen
              select: "{{macro_datediff('{{user.Var(\"max_timestamp_bw_tracks_pages_1\")}}')}}"
              dependencies:
                - max_timestamp_bw_tracks_pages_1
          #Churn features
          - entity_var:
              name: is_churned_10_days
              select: case when {{user.Var("days_since_last_seen")}} > 10 then 1 else 0 end
              description: Depending on the n value, it specifies if there is any activity observed in the last 10 days.
              dependencies:
                - days_since_last_seen
      features:
        - max_timestamp_bw_tracks_pages_1
        - is_churned_10_days