models:
  - name: user_id_graph
    model_type: id_stitcher
    model_spec:
      validity_time: 24h
      entity_key: user
      edge_sources:
        - from: inputs/app_identifies
        - from: inputs/app_user_roles
        - from: inputs/app_organizations
        - from: inputs/app_user_accounts
        - from: inputs/app_users
        - from: inputs/cio_email_converted
        - from: inputs/mkt_identifies
        - from: inputs/mkt_identifies_historical
        - from: inputs/mkt_pages
        - from: inputs/mkt_pages_historical
        - from: inputs/mkt_basin_and_sf_enrich
        - from: inputs/mkt_form_submit
        - from: inputs/mkt_form_submit_historical
        - from: inputs/sf_lead
        - from: inputs/sf_contact
        - from: inputs/mkt_qualified_meeting_booked
        - from: inputs/mkt_qualified_email_captured
  - name: account_id_graph
    model_type: id_stitcher
    model_spec:
      validity_time: 24h
      entity_key: account
      edge_sources:
        - from: inputs/app_user_roles
        - from: inputs/app_organizations
        - from: inputs/app_user_accounts
        - from: inputs/sf_account
        - from: inputs/sf_contact
        - from: inputs/sf_lead

  - name: attribution_scores
    model_type: attribution_report
    model_spec:
      entity_key: user
      # id_column_name: rudder_id #optional
      user_journeys:
        - from: inputs/mkt_pages
          timestamp: timestamp
          touch:
            utm_source: context_traits_utm_source
            utm_campaign: context_traits_utm_campaign
        - from: inputs/mkt_pages_historical
          timestamp: timestamp
          touch:
            utm_source: utm_source
      spend_inputs:
        - models/Union_Event_Data
      conversions:
        - name: sf_mql
          timestamp: sf_mql_date
          # value: user.Var("first_order_amount") -- optional
        - name: sf_iql
          timestamp: sf_iql_date

  - name: user_base_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h
      entity_key: user
      features:
        - sf_iql
        - sf_mql
        - sf_iql_date
        - sf_mql_date
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: sf_iql
          select: any_value(iql_c)
          from: inputs/sf_lead
          description: IQL flag from the Lead record in Salesforce
      - entity_var:
          name: sf_iql_date
          select: any_value(iql_date_c)
          from: inputs/sf_lead
          description: Timestamp of IQL flag being set in Salesforce
      - entity_var:
          name: sf_mql
          select: any_value(mql_c)
          from: inputs/sf_lead
          description: MQL flag from the Lead record in Salesforce
      - entity_var:
          name: sf_mql_date
          select: any_value(mql_date_c)
          from: inputs/sf_lead
          description: Timestamp of MQL flag being set in Salesforce