models:
  # - name: propensity_model
  #   model_type: propensity
  #   model_spec:
  #     entity_key: user
  #     training:
  #       predict_var: packages/feature_table/entity/user/is_churned_7_days
  #       predict_window_days: 7
  #       eligible_users: '*'
  #       max_row_count: 500000
  #       label_value: 1
  #       type: classification
  #       validity: day
  #     prediction:
  #       output_columns:
  #         percentile:
  #           name: percentile_classification_churn_7_days
  #           description: description1
  #         score:
  #           name: classification_churn_7_days
  #           description: description2
  #           is_feature: False
  #       eligible_users: '*'
  #     inputs:
  #       - packages/feature_table/entity/user/is_churned_7_days
  #       - packages/feature_table/entity/user/days_since_last_seen
  #       - packages/feature_table/entity/user/has_seen_recently
  #       - packages/feature_table/entity/user/last_seen_category
  #       - packages/feature_table/entity/user/n_orders_completed

  - name: training_Regression_model
    model_type: training_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      inputs:
        - packages/feature_table/models/shopify_user_features
        - packages/feature_table/models/rsRandomSQLModel
      ml_config:
        data:
          task: regression
          label_column: packages/feature_table/entity/user/days_since_last_seen
          prediction_horizon_days: 7
          eligible_users: '*'
          output_profiles_ml_model: ltv_regression_integration_test

  - name: prediction_regression_model
    model_type: prediction_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      training_model: models/training_regression_model
      inputs:
        - packages/feature_table/models/shopify_user_features
        - packages/feature_table/models/rsRandomSQLModel
      ml_config:
        data:
          task: regression
          label_column: packages/feature_table/entity/user/days_since_last_seen
          prediction_horizon_days: 7
          eligible_users: '*'
          output_profiles_ml_model: ltv_regression_integration_test
        outputs:
          column_names:
            percentile: percentile_regression_days_since_last_seen
            score: regression_days_since_last_seen
      features:
        - name: percentile_regression_days_since_last_seen
          description: description

