models:
  - name: traininG_model # Mix of small and capital letters to test ref standardization
    model_type: training_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      inputs:
        - packages/feature_table/models/shopify_user_features
      ml_config:
        data:
          label_column: is_churned_7_days
          prediction_horizon_days: 7
          eligible_users: 1=1
          output_profiles_ml_model: ltv_classification_integration_test
  - name: training_regression_model
    model_type: training_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      inputs:
        - packages/feature_table/models/shopify_user_features
      ml_config:
        data:
          task: regression
          label_column: days_since_last_seen
          prediction_horizon_days: 7
          eligible_users: 1=1
          output_profiles_ml_model: ltv_regression_integration_test
# - name: prediction_model
#   model_type: prediction_model
#   model_spec:
#     occurred_at_col: insert_ts
#     entity_key: user
#     training_model: models/training_model
#     inputs:
#       - packages/feature_table/models/shopify_user_features
#     ml_config:
#       data:
#         label_column: is_churned_7_days
#         prediction_horizon_days: 7
#         output_profiles_ml_model: ltv_classification_integration_test
