models:
  - name: propensity_model
    model_type: propensity
    model_spec:
      entity_key: user
      training:
        predict_var: packages/feature_table/entity/user/is_churned_7_days
        predict_window_days: 7
        eligible_users: '*'
        max_row_count: 500000
        label_value: 1
        type: classification
        validity: day
        new_materialisations_config:
          strategy: "auto"
          feature_data_min_date_diff: 14
          max_no_of_dates: 3
      prediction:
        output_columns:
          percentile:
            name: percentile_classification_churn_7_days
            description: description1
          score:
            name: classification_churn_7_days
            description: description2
            is_feature: False
        eligible_users: '*'
      inputs:
        - packages/feature_table/entity/user/max_timestamp_tracks
        - packages/feature_table/entity/user/max_timestamp_pages
        - packages/feature_table/entity/user/max_timestamp_bw_tracks_pages
        - packages/feature_table/entity/user/n_orders_completed
        - packages/feature_table/entity/user/gross_amt_spent_in_past_90_days
        - packages/feature_table/entity/user/days_since_last_seen
        - packages/feature_table/entity/user/is_churned_7_days
        - packages/feature_table/entity/user/has_seen_recently
        - packages/feature_table/entity/user/last_seen_category
        - packages/feature_table/entity/user/random_agg_event
        - packages/feature_table/entity/user/random_float_feature
        - packages/feature_table/models/rsRandomSQLModel

  - name: training_Regression_model
    model_type: training_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      inputs:
        - packages/feature_table/entity/user/is_churned_7_days
        - packages/feature_table/entity/user/days_since_last_seen
        - packages/feature_table/models/rsRandomSQLModel
      ml_config:
        data:
          task: regression
          label_column: packages/feature_table/entity/user/days_since_last_seen
          prediction_horizon_days: 7
          eligible_users: '*'
          output_profiles_ml_model: ltv_regression_integration_test
          new_materialisations_config:
            strategy: "manual"
            dates:
              - '2024-08-01,2024-08-07'
              - '2024-08-02,2024-08-08'
              - '2024-08-03,2024-08-09'

  - name: prediction_regression_model
    model_type: prediction_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      training_model: models/training_regression_model
      inputs:
        - packages/feature_table/entity/user/is_churned_7_days
        - packages/feature_table/entity/user/days_since_last_seen
        - packages/feature_table/models/rsRandomSQLModel
      ml_config:
        data:
          task: regression
          label_column: packages/feature_table/entity/user/days_since_last_seen
          prediction_horizon_days: 7
          eligible_users: '*'
          output_profiles_ml_model: ltv_regression_integration_test
        outputs:
          column_names:
            percentile: percentile_regression_days_since_last_seen
            score: regression_days_since_last_seen
      features:
        - name: percentile_regression_days_since_last_seen
          description: description

