# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsTest
  - name: sf_cortex_test
    model_type: sf_cortex
    model_spec:
      prompt: "The input field is a name entered by a person. Map it to a single value from the following list of standardised gender titles: [Male,Female,Other]. Return only standardised title, nothing else. {input[0]}"
      entity_key: user
      prompt_inputs:
        - gender
      llm_model_name: "mistral-7b"

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: gender
          select: max(first_name)
          from: inputs/rsTest
