models:
  - name: rudder_user_base_features_1
    model_type: feature_table_model
    model_spec:
      validity_time: 2m # 1 day
      entity_key: user
      vars:
        - entity_var:
            name: max_timestamp_bw_tracks_pages_1
            select: max(timestamp)
            from: inputs/rsTracks
      features:
        - max_timestamp_bw_tracks_pages_1
