
# Generated by CodiumAI
from SnowflakeConnector import SnowflakeConnector
import pandas as pd
from unittest.mock import Mock
import unittest
from snowflake.snowpark import Session
import snowflake.snowpark.types as T


class TestLabelTable(unittest.TestCase):
    def setUp(self) -> None:
        self.session = Session.builder.config('local_testing', True).create()
        self.connector = SnowflakeConnector()
        df = pd.DataFrame.from_dict({"COL1": ["2021-01-01 00:00:00", "2021-01-01 00:00:00"], 
                                     "COL2": ["value1", "value2"],
                                     "COL3": ["2021-01-01", "2021-01-01"],
                                     "COL4": ["2021-01-01 00:00:00+00:00", "2021-01-01 00:00:00+00:00"],}
                                    )
        self.table = self.session.create_dataframe(df)        
    
    def test_label_table_returns_only_required_cols(self):
        self.connector.get_table = Mock(return_value=self.table)
        label_column = "COL2"
        entity_column = "COL3"
        positive_class = "value1"
        actual = self.connector.label_table(self.session, 
                                            None, 
                                            label_column,
                                            entity_column, 
                                            positive_class)
        self.assertListEqual(actual.columns, [entity_column, label_column])
    def test_label_table_changes_label_value_for_classification(self):
        self.connector.get_table = Mock(return_value=self.table)
        label_column = "COL2"
        entity_column = "COL3"
        positive_class = "value1"
        actual = self.connector.label_table(self.session, 
                                            None, 
                                            label_column,
                                            entity_column, 
                                            positive_class)
        actual_label_col_vals = [v.as_dict()[label_column] for v in actual.collect()]
        expected_label_col_vals = [1, 0]
        self.assertListEqual(actual_label_col_vals, expected_label_col_vals)        
    def test_label_table_does_not_change_label_value_for_regression(self):
        self.connector.get_table = Mock(return_value=self.table)
        label_column = "COL2"
        entity_column = "COL3"
        actual = self.connector.label_table(self.session, 
                                            None, 
                                            label_column,
                                            entity_column, 
                                            None
                                            )
        actual_label_col_vals = [v.as_dict()[label_column] for v in actual.collect()]
        expected_label_col_vals = ["value1", "value2"]
        self.assertListEqual(actual_label_col_vals, expected_label_col_vals)        
