name: Integration Test - Redshift

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test-redshift:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8.15
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r tests/integration/requirements.txt

    - name: Run classifier training test
      run: python -m unittest tests/integration/redshift/train_classifier.py
      env:
          REDSHIFT_SITE_CONFIG: ${{secrets.REDSHIFT_SITE_CONFIG}}

    - name: Run regressor training test
      run: python -m unittest tests/integration/redshift/train_regressor.py
      env:
          REDSHIFT_SITE_CONFIG: ${{secrets.REDSHIFT_SITE_CONFIG}}
