name: Integration Test - Redshift

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'src/predictions/profiles_mlcorelib/py_native/attribution_report.py'
      - 'src/predictions/profiles_mlcorelib/py_native/llm.py'
      - 'src/predictions/profiles_mlcorelib/py_native/id_stitcher/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-test-redshift:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r tests/integration/requirements.txt

    - name: Run classifier test
      run: python -m unittest tests/integration/redshift/classifier.py
      env:
          REDSHIFT_SITE_CONFIG: ${{secrets.REDSHIFT_SITE_CONFIG_V2}}

    - name: Run regressor test
      run: python -m unittest tests/integration/redshift/regressor.py
      env:
          REDSHIFT_SITE_CONFIG: ${{secrets.REDSHIFT_SITE_CONFIG_V2}}
