name: Integration Test - BigQuery

on:
  pull_request:
    branches:
      - main1

jobs:
  integration-test-bigquery:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r tests/integration/requirements.txt

    - name: Run classifier test
      run: python -m unittest tests/integration/bigquery/classifier.py
      env:
          BIGQUERY_SITE_CONFIG: ${{secrets.BIGQUERY_SITE_CONFIG}}

    - name: Run regressor test
      run: python -m unittest tests/integration/bigquery/regressor.py
      env:
          BIGQUERY_SITE_CONFIG: ${{secrets.BIGQUERY_SITE_CONFIG}}
