name: Integration Pynative - Redshift

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test-redshift:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13
        cache: 'pip'

    - name: Install local mlcorelib
      working-directory: src/predictions
      run: pip3 install .

    - name: Run classifier test
      run: python -m unittest tests/integration/redshift/classifier1.py
      env:
          REDSHIFT_SITE_CONFIG: ${{secrets.REDSHIFT_SITE_CONFIG_V2}}
