name: publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be published'
        required: true
        type: string
      
jobs:
  profiles-mlcorelib:
    name: publish profiles-mlcorelib
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.release }}
      GH_TOKEN: ${{ secrets.PAT }}
    environment:
      name: ${{ inputs.environment }}
      url: https://pypi.org/p/profiles-mlcorelib
    permissions:
      id-token: write
    steps:
      - name: download
        shell: bash
        run: |
          gh release download ${VERSION} --repo github.com/rudderlabs/rudderstack-profiles-classifier --pattern "profiles_mlcorelib_${VERSION}.tar.gz" -O ./dist.tar.gz
          tar -zxvf dist.tar.gz
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/