name: publish
# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Version to be published'
#         required: true
#         type: string

on:
  pull_request:
    branches:
      - main
      
jobs:
  profiles-mlcorelib:
    name: publish profiles-mlcorelib
    runs-on: ubuntu-latest
    env:
      VERSION: '0.1.0'
      GH_TOKEN: ${{ secrets.PAT }}
    permissions:
      id-token: write
    environment:
      name: 'pypi-prod'
      url: https://pypi.org/p/profiles-mlcorelib
    steps:
      - name: download
        shell: bash
        run: |
          gh release download ${VERSION} --repo github.com/rudderlabs/rudderstack-profiles-classifier --pattern "profiles_mlcorelib-${VERSION}-*.whl"
      - name: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/