name: release
on:
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: 'Release version'
  #       required: true
  #       type: string
  pull_request:
    branches:
      - main
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      VERSION: 0.1.0-rc1
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: checkout branch to be released
        uses: actions/checkout@v4
        with:
          # Release from the main branch
          ref: prml-577-release-gha
          fetch-depth: 0
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: setup git config
        run: |
          git config --global user.email "devops-github-rudderstack@users.noreply.github.com"
          git config --global user.name "devops-github-rudderstack"
          
      - name: set version and create tag
        run: |
          VERSION=$VERSION make version
          git add . && git commit -m "chore: release ${VERSION}"
          git tag -a ${VERSION} -m "release ${VERSION}"

      - name: install dependencies
        run: pip3 install wheel setuptools
      
      - name: build wheel
        working-directory: src/predictions
        run: python setup.py sdist bdist_wheel
      
      - name: push tag and create release
        working-directory: src/predictions
        run: |
          git push origin prml-577-release-gha --tags
          gh release create ${VERSION} --generate-notes dist/*.tar.gz dist/*.whl